#!/bin/sh

PING_COUNT=5
LOGFILE=/var/log/wireless_watchdog

. /usr/local/etc/wireless_watchdog

if [ x"$DEV" = x ]; then
    echo missing DEV variable 1>&2
    exit 1
fi


if ! ping -c ${PING_COUNT} -q 8.8.8.8 >/dev/null ; then
    logger -p user.notice -t wireless_watchdog \
           Internet is unreachable, restarting $DEV
    date >>$LOGFILE
    echo restarting $DEV >>$LOGFILE
    /usr/bin/pkill wvdial >>$LOGFILE 2>&1
    sleep 7
    /usr/bin/wvdial & >>$LOGFILE 2>&1
fi


  
  
